name: Learn Issue Actions
run-name: ${{ github.run_id }} is creating a comment

on:
  issues:
    types: [opened]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
        shell: bash
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v4
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            This is a multi-line test comment for comment creation
            This issue is created at ${{ github.event.issue.created_at }}
            - With GitHub **Markdown** :sparkles:
            - Created by [create-or-update-comment][1]
            [1]: https://github.com/peter-evans/create-or-update-comment
          reactions: "+1"
