name: Learn Issue Actions
on:
  issues:
    types: [opened]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
